# Utiliza la imagen oficial de MySQL
FROM mysql:latest

# Define variables de entorno
ENV MYSQL_ROOT_PASSWORD=PASSWORD
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=PASSWORD

